import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from 'react';
import { AuthBootstrapProvider } from '@/components/auth/AuthBootstrapContext';
import { AuthRefreshBoundary } from '@/components/auth/AuthRefreshBoundary';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Suspense fallback={children}>
          <AuthBootstrapProvider>
            <AuthRefreshBoundary>{children}</AuthRefreshBoundary>
          </AuthBootstrapProvider>
        </Suspense>
      </body>
    </html>
  );
}
